### ISSUE TITLE
Possible bug: nested compose with bindings on same property name may bubble

### ISSUE THREAD

**Issue by bigopon** [aurelia/templating-binding#103]
**I'm submitting a bug report**

* **Library Version:**
@ latest

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.25

* **Browser:**
Chrome 54

* **Language:**
ESNext

* **Current behavior:**
**[Sample gist https://gist.run/?id=d6017efcd3ad31d02a05bdcf213cf17b](https://gist.run/?id=d6017efcd3ad31d02a05bdcf213cf17b)**

I couldn't manage to make the gist run, it keeps showing require is not a function
Nested compose with binding on same property name got change handler triggered when value of lower level changed.

Something like this

```html
<!-- app.html -->
<template>
  <h1>${message}</h1>
  <compose view-model.bind='level1ViewModel'></compose>
</template>

<!-- level1.html -->
<template>
  <span click.trigger='isEditing = 1'>${name}</span>
  <input if.bind='isEditing' value.bind='name'/>
  <compose view-model.bind='level2ViewModel'></compose>
</template>

<!--level2.html -->
<template>
  <span click.trigger='isEditing = 1'>${name}</span>
  <input if.bind='isEditing' value.bind='name'/>
</template>
```

Whenever clicking on span of `level2.html`, `input` of `level1.html` also shows. However, if I define like this in `viewModel` of `level2.js`:

```js
class Level2 {
  isEditing = 0
}
```

it wont trigger change in level1

* **Expected/desired behavior:**
should not trigger

**Comment by EisenbergEffect** [comment]
This has to do with inheritance that comes with the compose element. However, I'm not sure this is the way we intended it. @jdanyow Wasn't it only supposed to inherit when there's no view model provided?

**Comment by jdanyow** [comment]
All combinations of compose view/view-model inherit the outer scope. If `isEditing` is not defined on level2's view model, the binding system will find it in the outer scope (level1's view model).

closing this unless- @EisenbergEffect please re-open if compose is supposed to work differently depending on what attributes folks use.

**Comment by bigopon** [comment]
Maybe consider putting a note somewhere in the doc ? In cheatsgeet or gotcha section something ?
