### ISSUE TITLE
IE 11 has different behavior when using two-way binding and bindable callback function on a custom component

### ISSUE THREAD

**Issue by viljark** [aurelia/templating-binding#104]
**I'm submitting a bug report**

* **Library Version:**
major

* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
IE 11

**Current behavior:**
IE 11 has different behavior from latest Chrome, Edge, FF when triggering a change to parent with a bindable callback fn, using a two-way binding to pass value into the component and read it later inside the callback.

When the callback is triggered, the property used in two way binding has old value in IE11, in other browsers it is up to date. The value is updated, but later. 

See plnkr in IE11 and in Chrome for better description of the issue:
https://plnkr.co/edit/GJSLqPJFA8lMu1XSqAlx?p=preview

**Expected/desired behavior:**
Same behavior in all browsers.

**Comment by jdanyow** [comment]
The template looks like this:
```html
<input type="radio" 
        ref="inputElement"
        value.bind="value" 
        checked.bind="checked" 
        change.delegate="checkedHasChanged()"
 >
```

When the HTML is parsed by the browser, an input element is created. It's `attributes` property contains four items: `ref`, `value.bind`, `checked.bind` and `change.delegate`.

Some browsers will put the attributes in the same order as they appear in the markup. Others will alphabetize them, which impacts the order the bindings are evaluated.

Try doing something like this:

```html
<input type="radio" 
        ref="inputElement"
        value.bind="value" 
        checked.one-way="checked"       <---------- when the model value changes, the view is updated
        change.delegate="setChecked($event.target.checked)"
 >
```
```js
  ...
  ...
  setChecked(newValue) {
    this.checked = newValue;
    this.callback();
  }
  ...
  ...
```
