### ISSUE TITLE
Complex ValueConverter names not working

### ISSUE THREAD

**Issue by vec2k4** [aurelia/templating-binding#12]
Using the 'aurelia-skeleton-navigation v0.10.0', I tried to change the name of the 'UpperValueConverter' to 'MyUpperValueConverter':

``` javascript
export class MyUpperValueConverter
{
  toView(value)
  {
    return value && value.toUpperCase();
  }
}
```

I changed the HTML properly:

``` html
...
<div class="form-group">
  <label>Full Name</label>
  <p class="help-block">${fullName | my-upper}</p>
</div>
...
```

But the value converter is not recognized. It seems that the lexxer creates 5 tokens (fullName, |, my, -, upper) instead of 3 (fullName, |, my-upper) from the binding.

**Comment by EisenbergEffect** [comment]
This is fixed and will go out in the next release, probably tomorrow.
