### ISSUE TITLE
IE9 value.bind on <select> elements fails to load aurelia

### ISSUE THREAD

**Issue by doubleaa93** [aurelia/templating-binding#120]
**I'm submitting a bug report**

* **Library Version:**
1.1.5

**Please tell us about your environment:**
* **Operating System:**
windows 7x64

* **Node Version:**
8.9.1

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
webpack 3.8.1

* **Browser:**
IE 9

* **Language:**
Typescript 2.6.1

**Current behavior:**
Aurelia fails to load root component

**Expected/desired behavior:**
Should set root component. I created a gist but gist.run does not work on ie9
https://gist.run/?id=a4041f4375e2c7c2d6961594f81d7045

**Comment by jdanyow** [comment]
please refer to:

http://aurelia.io/docs/fundamentals/app-configuration-and-startup#bootstrapping-older-browsers
