### ISSUE TITLE
Dynamically filtered <option>-lists display the wrong selected value

### ISSUE THREAD

**Issue by Krossmaskinen** [aurelia/templating-binding#124]
* **Library Version:**
1.4.2

* **Operating System:**
Windows 10

* **Node Version:**
8.9.2

* **NPM Version:**
5.5.1

JSPM 0.16.53

* **Browser:**
all

* **Language:**
TypeScript

**Summary**
I have two select elements. They have option lists that are filtered by a value converter.

```
<select value.bind="selectedItem1" id="select1">
    <option repeat.for="item of itemList | filter:selectedItem2" model.bind="item"> ${item.name}
</select>
<select value.bind="selectedItem2" id="select2">
    <option repeat.for="item of itemList | filter:selectedItem1" model.bind="item"> ${item.name}
</select>
```

The value converter makes sure that the item selected in one list is not available as an option in the other list.

**Current behavior:**
I select the top option in #select1, and the top option in #select2.
Now I change the selection of #select1.
This results in #select2 option list being filtered, and now displays the new item on the same index as the previously selected value as the selected value.
Behind the scenes though, if you log out the selectedItem2, the correct item is still selected, even though another item is displayed in the view.

Example:
```
itemList = [
    {
        id: 1,
        name: 'one'
    },
    {
        id: 2,
        name: 'two'
    },
    {
        id: 3,
        name: 'three'
    }
]
```
if I choose 'one' in #select1, it disappears from the #select2 option list. I then select 'two' in the #select2, and it disappears from #select1 option list. So far so good.

If I now select 'three' on the first list, #select2 will now show 'one' as the selected value, even though 'two' is the real selected value.

**Expected/desired behavior:**
The option lists should be filtered but the displayed selected values should stay the same

**Comment by bigopon** [comment]
Also tracked in aurelia/binding#521

**Comment by bigopon** [comment]
@Krossmaskinen fix for this is at https://github.com/aurelia/binding/pull/677
