### ISSUE TITLE
Declarative Computed Values (let) is broken: LetInterpolationBindingExpression is not defined 

### ISSUE THREAD

**Issue by graycrow** [aurelia/templating-binding#129]
**I'm submitting a bug report**

* **Library Version:**
1.5.1

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
10.12.0

* **NPM Version:**
6.4.1

* **Webpack AND Version**
webpack 4.23.1

* **Browser:**
all

* **Language:**
TypeScript 3.1.3

**Current behavior:**
It looks like `let` functionality is broken.

New aurelia-cli project. I'm using the examples form the documentation. For Declarative Computed via Interpolation:
```
 <let full-name="${firstName} ${lastName}"></let>
    <div>
      First name:
      <input value.bind="firstName">
      Last name:
      <input value.bind="lastName">
    </div>
    Full name is: "${fullName}"
```
It throws an error: `ReferenceError: LetInterpolationBindingExpression is not defined at TemplatingBindingLanguage.createLetExpressions`. I checked a builds in the `dist`, and yes, it's not defined there, but exists on `src`. Something went wrong during build?

Also, In the case of Declarative Computed via Expression
```
   <let full-name.bind="firstName + ' ' + lastName"></let>
    <div>
      First name:
      <input value.bind="firstName">
      Last name:
      <input value.bind="lastName">
    </div>
    Full name is: "${fullName}"
```
it works but shows a few warnings (which I assume is a bug as well): `Detected string literal in let bindings. Did you mean "class.bind=au-target" or "class=${au-target}" ?`

**Comment by bigopon** [comment]
The initial release of this had few issues. Its fixed in latest version. Can you give it a try?

**Comment by bigopon** [comment]
@graycrow Also pls upgrade both `template` and `templating-binding` to latest version. It will fix all the issues you encountered

**Comment by graycrow** [comment]
@bigopon I'm using `aurelia-templating-binding` v1.5.1 and `aurelia-templating` v1.10.0. Both are the most recent versions.

**Comment by bigopon** [comment]
@graycow then you will probably need to update your package lock. Or delete it and reinstall. At least thats what i believe. Can you help do a fresh install and check?

**Comment by graycrow** [comment]
I probably found the issue. In the `build/paths.js`, `.js` extension is missing on line 32.
https://github.com/aurelia/templating-binding/blob/393cf058981b86465d63a6a936a6486e943af848/build/paths.js#L32

Fixed it and made a new build of `aurelia-templating-binding`, but now the application throws `Error: BindingLanguage must implement inspectTextContent().`

**Comment by graycrow** [comment]
@bigopon, I created a new project from scratch yesterday in order to isolate the issue. And I checked the files in `the node_modules` directory, they are the most recent versions. And I think I found something, check my previous comment please.

**Comment by bigopon** [comment]
Oh dear. I missed that. Would be awesome if you could create a PR to fix that. No need to build though. Thanks for pointing that out! @graycrow

**Comment by bigopon** [comment]
I think the error you got ia related to packgage lock. I ve seen them few times and they were that.

**Comment by graycrow** [comment]
I recreated the project from scratch again, applied the fix and now getting `sourceExpression.evaluate is not a function  at ChildInterpolationBinding.bind` error if interpolation binding is used.
https://github.com/aurelia/templating-binding/blob/393cf058981b86465d63a6a936a6486e943af848/src/interpolation-binding-expression.js#L179

**Comment by bigopon** [comment]
@graycrow can you show yournusage that led to the error?

**Comment by graycrow** [comment]
Sure, `app.ts`:
```
import { bindable } from "aurelia-framework";

export class App {
  message = 'Hello World!';
  @bindable firstName;
  @bindable lastName;
}
```

`app.html`:
```
<template>
<let full-name="${firstName} ${lastName}"></let>
    <div>
      First name:
      <input value.bind="firstName">
      Last name:
      <input value.bind="lastName">
    </div>
    Full name is: "${fullName}"
</template>
```

**Comment by graycrow** [comment]
If I put a breakpoint on ChildInterpolationBinding constructor, it called twice and first time `sourceExpression` is `AccessScope {isAssignable: true, name: "fullName", ancestor: 0}` and second time is a garbage, string `u`.

Edit. I assume `u` comes from second character in `fullName`, because on my main project the variable name is `addressLine` and broken `sourceExpression` equals to `d`.

**Comment by graycrow** [comment]
Found it. In `let-interpolation-expression.js` in `createBinding()` parameter order is wrong in the constructor call. Instead of  <strike>`this.observerLocator, this.parts,` should be `this.parts, this.observerLocator,`</strike>  `this.parts, this.targetProperty,`  should be `this.targetProperty, this.parts,`


https://github.com/aurelia/templating-binding/blob/393cf058981b86465d63a6a936a6486e943af848/src/let-interpolation-expression.js#L24

Edit: correct parameters

**Comment by bigopon** [comment]
@graycrow Awesome. Not sure why it's so wrong but glad you helped figured it out.

**Comment by bigopon** [comment]
@graycrow @EisenbergEffect this can be closed
