### ISSUE TITLE
Let expression parsing and auto-generated let element attributes.

### ISSUE THREAD

**Issue by graycrow** [aurelia/templating-binding#132]
**I'm submitting a bug(?) report**

* **Library Version:**
1.5.1

* **Operating System:**
Windows 8.1

* **Node Version:**
10.12.0

* **NPM Version:**
6.4.1

* **Webpack AND Version**
webpack 4.23.1

* **Browser:**
all

* **Language:**
TypeScript 3.1.3

**Current behavior:**

I mentioned this in the previous issue (#129), but I think it's deserves a separate issue.

Lets assume I have a let element: 
```
<let full-name="${firstName} ${lastName}"></let>
```

It's not rendered on the page, but internally it's gets passed to `TemplatingBindingLanguage.createLetExpressions()` in this form:

```
<let full-name="${firstName} ${lastName}" class="au-target" au-target-id="1"></let>
```

Please note that auto-generated attributes `class` and `au-target-id`. The problem is that `createLetExpressions` threats all attributes equally. And because they are not typical binding attributes it throws a warning, in this particular case 2 of them:
```
[templating-binding-language] Detected string literal in let bindings. Did you mean "class.bind=au-target" or "class=${au-target}" ?
[templating-binding-language] Detected string literal in let bindings. Did you mean "auTargetId.bind=1" or "auTargetId=${1}" ?
```

It may look harmless, but I have I feeling that it's not that harmless because now I'm investigating some issues in my project when introducing `let` elements into the code causing last items in the near `repeat.for` elements become undefined.

**Comment by bigopon** [comment]
This should be fixed by the latest `templating` commit https://github.com/aurelia/templating/commit/93fa9cc7ac3f51cff47fb9353110f26bdf20cea2

It's been released. Can you give it a try? @graycrow

**Comment by graycrow** [comment]
I afraid it's not released  yet. Last release is v1.10.0 from Sep. 30 and your commit is from Oct. 12. But I glad that it's fixed. I will apply it manually and check.

**Comment by bigopon** [comment]
@graycrow I thought it was release, that's why I kept asking you to upgrade. Sorry for that.
@EisenbergEffect I think we should release this asap to avoid unexpected behavior for folks along with the PRs from @graycrow in `templating-binding`

**Comment by graycrow** [comment]
@bigopon no rush, because after applying all commits from `aurelia-templating` I started to get `Cannot read property 'behaviorInstructions' of undefined` error.

**Comment by graycrow** [comment]
@bigopon `auTargetID` is undefined on [line 323 ](https://github.com/aurelia/templating/blob/bbdbc43ec891b54475413ec153de35080da9a5fd/src/view-compiler.js#L323) in `aurelia-templating/view-compiler.js` , because you moved assignment to the line 329. This leads to instruction  being added to `instructions` under `undefined` key instead of `1`. And then at [line 471](https://github.com/aurelia/templating/blob/bbdbc43ec891b54475413ec153de35080da9a5fd/src/view-factory.js#L471) in `view-factory.js` `instructable.getAttribute('au-target-id')` is 1, but this key does not exists in instructions.

Edit: added line number

**Comment by bigopon** [comment]
@graycrow Oh thanks for pointing that out too. 🤦‍♂️  This bug wasn't easily caught in test, I oversaw this. Here is a fix for that https://github.com/aurelia/templating/pull/651

**Comment by bigopon** [comment]
@graycrow @EisenbergEffect This can be closed
