### ISSUE TITLE
change.delegate does not work inside of web components

### ISSUE THREAD

**Issue by Archelyst** [aurelia/templating-binding#151]
**I'm submitting a bug report**
Not sure if this is the right place to post it though...

* **Library Version:**
1.5.3

**Please tell us about your environment:**
* **Operating System:**
OSX 10.15

* **Node Version:**
12

* **Browser:**
Firefox 92

* **Language:**
TypeScript 3.9.10

**Current behavior:**
Nothing happens when I put a `change.delegate` on an input when the app lives inside of a web component. `change.trigger` works.

**Expected/desired behavior:**
It should work.

**Comment by bigopon** [comment]
`change.delegate` relies on the the event being propagated to the document and delegated back to some handlers. This won't work well in a web-component shadowDOM heavy world. Please use `change.trigger`, we will be updating our stance on `change.delegate` vs `change.trigger`.
