### ISSUE TITLE
Proposed convention / constraint for multi-parameter value converters

### ISSUE THREAD

**Issue by BalassaMarton** [aurelia/templating-binding#19]
I don't know if there will be any 'out of the box' converters, but I think converters should always take zero or one parameter, and it should be an object when there are more than one argument for the conversion. In many scenarios, template authors / UI designers work separately from coders, and even a converter with 2 parameters can obfuscate the template. Consider, for example, the below snippet, taken from the [latest blog entry](http://eisenbergeffect.bluespire.com/binding-with-value-converters-in-aurelia/#):

``` html
<tr repeat.for="repo of repos | sort:column.value:direction.value | take:10">
```

There are two problems with this syntax. (1) The colons split the conversion declaration into three parts, and the reader could think that the parts are on the same syntactic level. At best, it produces poor readability. (2) The template author needs to know the order of parameters, but that's not even trivial for a coder (that's why we push Ctrl+Shift+Space in VS like a monkey), let alone for a designer. So, for the above example, the new declaration would look something like this:

``` html
<tr repeat.for="repo of repos | sort: {key: column.value, direction: direction.value} | take: 10">
```

Note that this change does not require any modification in the parser, it's a convention that should be followed to minimize confusion. One additional benefit of this convention is that a converter can define a default value for any parameter, and the template author can omit any parameter, regardless of order.

**Comment by jdanyow** [comment]
@BalassaMarton sounds like a nice convention.  The good news is Aurelia will allow you to write converters in this manner soon.  We're actively working on supporting object literals in converter parameters- keep an eye on https://github.com/aurelia/templating-binding/issues/10 for updates on the progress.

**Comment by jdanyow** [comment]
@BalassaMarton object parameter support has been released.  I've updated the sample application / blog post to include an example:

http://jdanyow.github.io/aurelia-converters-sample/#object-parameters

**Comment by EisenbergEffect** [comment]
Closing this now that we've introduced the fix for object binding.

**Comment by talski** [comment]
@jdanyow it seems that this sample app need some update
