### ISSUE TITLE
custom attribute mapping to support polymer camelCased attributes

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-binding#21]
So we don't lose track of this...

[gitter discussion](https://gitter.im/Aurelia/Discuss?at=54f61850e172474214a81dd6)

current work-around:

``` javascript
import {TemplatingBindingLanguage} from 'aurelia-framework'; // or from 'aurelia-templating-binding'

.. resolve TemplatingBindingLanguage from container...

function mapPolymerElementAttributes(elementName){
    Polymer.elements
        .find( ele => ele.name === elementName )
        .getAttribute('attributes').split(' ')
        .forEach( attr => {
            if (attr.toLowerCase() !== attr)
                bindingLang.attributeMap[attr.toLowerCase()] = attr;
        });
}
```

further work required to avoid stomping on built-in attribute maps and to support scenario where polymer element 1 has a fooBar attribute and polymer element 2 has a fooBAR attribute.

**Comment by olanod** [comment]
This should work in the meantime, but in the not so far future when next Polymer version launches we can use the convention of dashed attributes to camel case. They are putting that functionality back for the 0.8 release.
