### ISSUE TITLE
one-time interpolation binding expressions

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-binding#24]

**Comment by jdanyow** [comment]
supported in next release

**Comment by schatekar** [comment]
@jdanyow Is this feature released? Apologies for a dumb question but I tried following your commit and got lost. I need to know if the following will work?

`<input type="text" data-original="${name | oneTime}" value.bind="name" />`

I specifically interested in the `| oneTime` part.

**Comment by jdanyow** [comment]
yep, the symbol for binding behaviors is `&` (as opposed to `|` for value converters).

``` html
<input type="text" data-original="${name & oneTime}" value.bind="name" />
```

Here's the standard way to write a one-time binding. This will be a bit more light-weight in terms of parsing and binding:

``` html
<input type="text" data-original.one-time="name" value.bind="name" />
```
