### ISSUE TITLE
String interpolation renders nothing for number 0

### ISSUE THREAD

**Issue by martingust** [aurelia/templating-binding#3]
String interpolation in a template renders empty string when parsing number 0.

**Comment by jdanyow** [comment]
Anyone already working on this?  I'd like to take a crack at it if not.

**Comment by EisenbergEffect** [comment]
I think @martingust is working on it. See if you can get him on gitter.

**Comment by martingust** [comment]
@jdanyow I'm on it, should be able to get it in later today.

**Comment by jdanyow** [comment]
k- no rush, I just saw it in the gitter
