### ISSUE TITLE
Make the attributemap a single instance that lives in the DI and can be appended by apps

### ISSUE THREAD

**Issue by Alxandr** [aurelia/templating-binding#32]
Currently, if you encounter an attribute - property pair with different names (like `colspan` != `colSpan`) it has to be added to aurelia, and you have to wait for a new release.

Or, you could inject the binding-language, hoping that it's the default one, and use a private API to extend it yourself.

I'm suggesting it should exist as a simple public API used by the binding language instead, so I can do stuff like this in my `main`:

``` javascript
const attributeMap = di.get(AttributeMap);
attributeMap.register('foo-bar', 'fooBar');
aurelia.start......;
```

Note, it doesn't have to be exactly like that, it's only a suggestion to the API. The point is to have something simple and extendible, with a public API surface.

**Comment by jdanyow** [comment]
:+1: 

Would be nice if attribute maps could be scoped to a particular node type as well.

https://github.com/aurelia/binding/issues/80#issuecomment-102217602

**Comment by EisenbergEffect** [comment]
@jdanyow Any thoughts on this? Should we make some improvements for this?

**Comment by jdanyow** [comment]
I think we need to implement this as well as support for mapping specific node-name/attr-name combinations.  Will put this in my queue.

**Comment by Alxandr** [comment]
@jdanyow I suggest just extending the api to

```
attributeMap.get(node.tagName, 'attribute-name');
```

Would allow it to choose to ignore or care about the tag name on it's own.

**Comment by jdanyow** [comment]
implemented in https://github.com/aurelia/templating-binding/commit/4f3e91198a0102ca82fc791d5b69a77cfff94e43
