### ISSUE TITLE
Support for ES6 Sets

### ISSUE THREAD

**Issue by chandmk** [aurelia/templating-binding#34]
Binding repeat.for over a set does nothing

``` javascript

export class Test{
  constructor(){
    this.list = new Set(["foo", "bar", "foo"]);
  }
}
```

``` html
<template>
  <section>
    <ul>
      <li repeat.for="l of list">${l}</li>
    </ul>
</section>
</template>
```

Following works fine

```
this.list = Array.from(new Set(["foo", "bar", "foo"]))
```

**Comment by EisenbergEffect** [comment]
@jdanyow @martingust How hard would it be to add this do you think?

**Comment by martingust** [comment]
@jdanyow @EisenbergEffect We will need to patch a Set observer and update the repeater to handle Set object, I think the current `for` syntax should be good already . A lot of work we could grab from the Map implementation or maybe even refactor some stuff to handle both Map and Set objects. It would be nice to have this in place for beta. Maybe we could split up some work, what you guys think?

**Comment by jdanyow** [comment]
:+1: looks like a lot of the work you've done for Map can be used for Set.  Do you guys think it's worth making the repeat pluggable so users can add implementations for other collection implementations or is it better to handle the core ES6 cases as we have been and use converters for other cases?

**Comment by EisenbergEffect** [comment]
@jdanyow If you don't think that would be too hard, I think that's a great idea.

**Comment by martingust** [comment]
@jdanyow @EisenbergEffect That would be pretty cool. Another idea since its all just an array in the end, maybe we could handle everything, Map, Set etc, only in `binding`and always provide the repeater with arrays no matter of underlying type. haven't really thought it through or tested anything but it would remove a lot of duplicate logic in the repeater.
