### ISSUE TITLE
Interpolation of || (or)

### ISSUE THREAD

**Issue by akircher** [aurelia/templating-binding#37]
Currently `${ dynamic || 'default' }` interpolates to true rather than 'default' when dynamic is falsey.  The workaround is to do `${ dynamic ? dynamic : 'default'}` however it seems that the former should work as well.  Haven't tested with `&&` but would expect a similar issue as well.

**Comment by jdanyow** [comment]
issue is here:  https://github.com/aurelia/binding/blob/master/src/ast.js#L482

@EisenbergEffect let me know if you want me to work on this.

**Comment by jdanyow** [comment]
Should have mentioned-  it looks like the values are intentionally coerced to booleans.  I don't know if there are any pitfalls to changing this but can look into it.  @EisenbergEffect - if you recall the logic behind this let me know.

**Comment by EisenbergEffect** [comment]
@jdanyow It's literally in the AST's evaluation logic I believe.
