### ISSUE TITLE
Different binding attribute notations - consolidation suggestion

### ISSUE THREAD

**Issue by litera** [aurelia/templating-binding#4]
We can manually override default binding strategy `value.bind` by providing it as i.e. `value.one-way`. I suggest this be changed to rather use a different convention so we're always referring to the same thing but with _sub_ definition as `value.bind.one-way="somePropertyName"`. I think this would be better as it directly implies which default we're manually defining.

**Comment by EisenbergEffect** [comment]
I'm hesitant to add an additional dot into the mix. I appreciate the suggestion. For the moment, we are going to stick with the syntax we have. We may re-evaluate before we hit beta though. Thanks!
