### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by CarlosOnline** [aurelia/templating-binding#41]
1. Please provide more examples (stand alone github projects) for each feature described in the docs.
2. Please provide a TOC for objects, methods, apis, attributes.
3. Please provide a nice reference manual that has a page for each object, api, attribute.

**Comment by jdanyow** [comment]
All this is in the works- check here:  https://github.com/aurelia/documentation/issues/76

Or here: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Aaurelia+documentation
