### ISSUE TITLE
throw when interpolation is used in image src

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-binding#47]
Related to https://github.com/aurelia/templating-resources/pull/76

https://github.com/aurelia/templating-binding/blob/master/src/binding-language.js#L205

**Comment by capaj** [comment]
@jdanyow thanks for creating this issue and proposing quite a good solution. Will open another PR if I will find the time.

**Comment by EisenbergEffect** [comment]
I don't think we should throw...but we did fix this I think by removing the interpolated attributes. So, should be good to go.
