### ISSUE TITLE
Checkbox binding issue for array elements

### ISSUE THREAD

**Issue by shabalin** [aurelia/templating-binding#58]
Please check this http://plnkr.co/edit/0dv37svfh2FflZvLdZ7n out

**Comment by EisenbergEffect** [comment]
This relates to the fact that you are binding to an undefined property. If you add the selection property to your model, the problem goes away. It's always better to define the properties, not just for Aurelia but also for improved performance in the JS VM.

**Comment by shabalin** [comment]
thanks a lot, Rob!
