### ISSUE TITLE
Delegated Events Firing For Disabled Elements

### ISSUE THREAD

**Issue by Ixonal** [aurelia/templating-binding#59]
I have the following...

``` HTML
<button class="btn btn-primary" click.delegate="testAlert()" disabled="disabled">clicky?</button>
```

Where "testAlert" just fires an alert. The button is properly disabled, but when I click it, the alert displays. If I change it to "trigger" instead of "delegate", the event doesn't fire, as one would expect, so no alert. Shouldn't the event not be firing on delegate as well as trigger?

**Comment by jdanyow** [comment]
related to https://github.com/aurelia/binding/issues/163

**Comment by EisenbergEffect** [comment]
Closing this as a duplicate
