### ISSUE TITLE
Error while...i don't even know how to explain.

### ISSUE THREAD

**Issue by betrayedjinn** [aurelia/templating-binding#63]
Hi,

i just updated to the latest aurelia version and there seems to be an issue with my paging control.
First paging works fine, from then on i get an error `cannot read property p of undefined.` where `p` is my `repeat.for` variable.

``` javascript
Uncaught TypeError: Cannot read property 'p' of undefined
  evaluate @ aurelia-binding.js:1039
  evaluate @ aurelia-binding.js:1294
  evaluate @ aurelia-binding.js:1005
  interpolate @ aurelia-templating-binding.js:423
  call @ aurelia-templating-binding.js:410
  callSubscribers @ aurelia-binding.js:190
  call @ aurelia-templating.js:2812
  flushMicroTaskQueue @ aurelia-task-queue.js:110
  (anonymous function) @ aurelia-task-queue.js:60
```

Every time this error occurres the `source` in `InterpolationBinding.prototype.interpolate` is null.
Can someone tell me why this happens?

Thanks.

**Comment by EisenbergEffect** [comment]
@jdanyow @martingust Not sure which of you is the best person to look at this. Either of you have an idea off the top of your head? It could be related to the repeater implementation changes or the new binding system changes.

**Comment by jdanyow** [comment]
will have a fix for this in a minute

**Comment by jdanyow** [comment]
@EisenbergEffect this is all set.  @paranoxx's issue requires a release of `templating-binding`. Fixed the corresponding issue in `binding` so that should be released as well.

**Comment by EisenbergEffect** [comment]
I will get the release out later this evening. Thanks!

**Comment by betrayedjinn** [comment]
Thanks for the release.
