### ISSUE TITLE
"for" attribute with string interpolation gets removed from <ul> element

### ISSUE THREAD

**Issue by DarienFord** [aurelia/templating-binding#64]
I have a component which I reuse in different parts of the app.  In some cases, it is instantiated by different parent components.

I'm using the mdl lite framework from google and it uses the `for` attribute on a UL to determine how and when to display a drop down menu.

To facilitate this, I need to generate unique IDs for each instance of my component. 
I have the view model generating an ID appropriately, but as soon as I put a variable into the `for` attribute, the attribute does not get rendered on the DOM.

``` html
<ul for="a">
    <!--- for is rendered -->
    </ul>
    <ul for="a${instance}">
    <!-- for is not rendered -->
    </ul>
```

**Comment by jdanyow** [comment]
Will fix this as part of https://github.com/aurelia/templating-binding/issues/32

What's happening is 'for' maps to the htmlFor dom api which makes sense for a label el but not for a ul.

**Comment by DarienFord** [comment]
Thanks!

**Comment by jdanyow** [comment]
fixed in https://github.com/aurelia/templating-binding/commit/4f3e91198a0102ca82fc791d5b69a77cfff94e43
