### ISSUE TITLE
Create a reference as object property

### ISSUE THREAD

**Issue by heruan** [aurelia/templating-binding#66]
I'm trying to reference an `input` inside a `repeat.for` binding, i.e.

``` html
<div repeat.for="prop of properties">
  <input type="text" name="${prop}" ref="$parent.elements[prop]">
</div>
```

but the VM `elements` object stays empty. Is it possibile to reference elements using an object?

**Comment by EisenbergEffect** [comment]
`ref` doesn't accept a binding expression, only a name for the reference.

**Comment by heruan** [comment]
Since I'm facing numerous cases where a `ref.bind` would be very useful, I'd like to know if it could be an open discussion or the decision for the `ref` custom attribute to be limited to a name reference is final.

Take for example a simple view with a `with` binding:

``` html
<template>
  <section with.bind="entity">
    <form ref="entityForm"></form>
  </section>
  <section with.bind="entity.related">
    <form ref="relatedForm"></from>
  </section>
</template>
```

This will clutter `entity` and `entity.related` objects adding `entityForm` and `relatedForm` attributes. Having something like this would be very useful:

``` html
<template>
  <section with.bind="entity">
    <form ref.bind="$parent.entityForm"></form>
  </section>
  <section with.bind="entity.related">
    <form ref.bind="$parent.relatedForm"></from>
  </section>
</template>
```

This is obviously a naïve example, but think about nested elements and `repeat.for`s!

What do you think?

**Comment by heruan** [comment]
I wrote this custom attribute, I'll use this instead of `ref`. Maybe they could be merged together?

``` javascript
import {inject} from 'aurelia-dependency-injection';
import {customAttribute} from 'aurelia-templating';
import {bindingMode} from 'aurelia-binding';

@inject(Element)
@customAttribute('element', bindingMode.twoWay)
export class ElementCustomAttribute {

    constructor(element) {
        this.element = element;
    }

    attached() {
      this.value = this.element;
    }

}
```
