### ISSUE TITLE
Optimize interpolation bindings with only a single child binding

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-binding#67]

**Comment by jdanyow** [comment]
@EisenbergEffect I looked into this, here's what I found:

The idea was to return a `BindingExpression` instead of an `InterpolationBindingExpression` when there was only a single interpolation instance in the textContent/attrValue.

I added some logic to `TemplatingBindingLanguage` to do this:

``` js
  createBindingExpression(resources, attrName, attrValue) {
    let parts = this.parseContent(attrValue);
    if (parts === null) {
      return null;
    }

    if (parts.length === 3) {
      let sourceExpression = parts[1];
      if (parts[0] !== '') {
        sourceExpression = new Binary('+', new LiteralString(parts[0]), sourceExpression);
      }
      if (parts[2] !== '') {
        sourceExpression = new Binary('+', sourceExpression, new LiteralString(parts[2]));
      }
      return new BindingExpression(
        this.observerLocator,
        this.attributeMap[attrName] || attrName,
        sourceExpression,
        bindingMode.oneWay,
        resources.lookupFunctions,
        attrName
      );
    }

    return new InterpolationBindingExpression(
      this.observerLocator,
      this.attributeMap[attrName] || attrName,
      parts,
      bindingMode.oneWay,
      resources.lookupFunctions,
      attrName
    );
  }
```

This almost worked but doesn't convert the expression value to a string and doesn't handle null/undefined values either.  I could create a more complex binding expression to handle this but decided this was not a good idea, it was already getting complex with potential for multiple Binary and LiteralString expressions with the code above.  I started to go down the road of creating a special value converter  to avoid further nesting of expressions- something like this:

``` js
import {valueConverter} from 'aurelia-binding';

@valueConverter('auInterpolation')
export class InterpolationValueConverter {
  toView(value, left, right) {
    if (left === undefined) {
      left = '';
    }
    if (right === undefined) {
      right = '';
    }
    value = value === null || value === undefined ? '' : value.toString();
    return left + value + right;
  }
}
```

But then I realized this would impact the build of templating-binding due to this resource needing to be "globalized"....

My next thought was to create a special type of Expression to handle this scenario.  But this would need to be exported by binding otherwise templating-binding would need to monkey patch binding's Unparser.

So now I'm thinking maybe we ought to create a dedicated "SingleInterpolationBinding" class for this to avoid the current two-level InterpolationBinding+ChildInterpolationBinding situation we have now.

What do you think?  Do any of these sound like good ideas or should I table this for now?

**Comment by EisenbergEffect** [comment]
How complicated would the SingleInterpolationBinding class be, do you think? If it's not much code, then we could try that out.

**Comment by jdanyow** [comment]
this was addressed in a previous release
