### ISSUE TITLE
Standalone template-binding

### ISSUE THREAD

**Issue by tomalec** [aurelia/templating-binding#68]
Forgive me, if it's a stupid question, but I'm new to Aurelia.

Is it possible to run standalone Aurelia modules e.g. aurelia-template-binding?

I have managed to get trough "Getting started" and make my HTML bind with JS view-model. The thing is, I would like to use only this feature, so I would like to reduce the overhead (bootstrapper, routing, and other Aurelia features) and just bound my HTML to JSON view-model.

If and how can I do so?

**Comment by jdanyow** [comment]
It's possible to use certain libraries by themselves (eg `aurelia-event-aggregator`, `aurelia-dependency-injection`).  Other libraries such as the templating and binding related items are split up by function to enable scenarios like using aurelia's templating engine with a binding implementation designed to work with native controls.  Or maybe using aurelia's templating and binding libraries with a templating-binding implementation (the language/syntax impl) that mimics knockout or angular's syntax.

These are the top-level components you'd need:
1. `aurelia-templating`: This component knows how to compile an html template into a "view factory" that can create views with their bindings, etc
2. `aurelia-binding`: This component knows how to bind to a variety of object/element/properties
3. `templating-binding`: This is the "binding language/syntax", which is separate from the `aurelia-templating`, to enable multiple syntax implementations, etc
4. `templating-resources`: This has the implementation of various binding commands such as `repeat`, `if`, `show`, `compose`, etc.

These in turn have dependencies on tiny, lower-level components such as `aurelia-task-queue` and `aurelia-metadata`.

[Here's an example](https://github.com/aurelia/templating-resources/blob/master/test/repeat-integration.spec.js) of how you could use them in a stand-alone fashion, in this case we're standing up a minimal templating/binding setup for integration testing purposes.

All that said, I would stick to using the bootstrapper + framework which takes care of hooking all this stuff up for you (bootstrapper and framework are tiny libraries that essentially roll all this stuff together for you and give you app startup etc).  Things like the router, event-aggregator, etc are not required.
