### ISSUE TITLE
Terser syntax for class bindings

### ISSUE THREAD

**Issue by glen-84** [aurelia/templating-binding#69]
We currently have to do:

``` html
<div class="${isActive ? 'active' : ''} ${isDisabled ? 'disabled' : ''}">
```

Angular has this syntax:

``` html
<div [ng-class]="{active: isActive, disabled: isDisabled}">
```

Have you considered supporting a terser syntax?

**Comment by jdanyow** [comment]
We definitely need to get this implemented.  More info/discussion here:  https://github.com/aurelia/templating-binding/issues/23

**Comment by glen-84** [comment]
Apologies for the duplicate. I saw that issue, but I didn't know that it was the same thing. Just to confirm, can you also use an object literal like `<div class.bind="{danger: false}">`?

**Comment by jdanyow** [comment]
no worries- yes, your object literal example is what we want to support

**Comment by glen-84** [comment]
Cool, thanks. =)
