### ISSUE TITLE
Binding table cells to a Map

### ISSUE THREAD

**Issue by heruan** [aurelia/templating-binding#70]
I'm building a dynamic `<table>` where columns are bound to a schema described in a [Map](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map) object. E.g.,

``` html
<table>
  <thead>
    <tr>
      <th repeat.for="[name, schema] of columns">${name}</th>
    </tr>
  </thead>
</table>
```

When `columns.set("new", { sortable: true })` the column is correctly added to the table, but when `columns.delete("new")` I get this error:

```
Uncaught TypeError: Cannot read property 'firstChild' of undefined
    getAnimatableElement @ aurelia-templating.js:1096
    removeAt @ aurelia-templating.js:1247
    handleChanges @ map-collection-strategy.js:83
    handleCollectionChanges @ repeat.js:172
    call @ repeat.js:62
    callSubscribers @ aurelia-binding.js:219
    call @ aurelia-binding.js:715
    flushMicroTaskQueue @ aurelia-task-queue.js:110
    (anonymous function) @ aurelia-task-queue.js:60
```

Am I doing something wrong or is this a bug?

**Comment by jdanyow** [comment]
same error is happening here https://github.com/aurelia/binding/issues/239

**Comment by martingust** [comment]
Fixed in https://github.com/aurelia/templating-resources/commit/7f245ce3b490fa82cae20103281b665a07cf3eb2.

**Comment by heruan** [comment]
Thank you @martingust ! How can I test it on my app? Currently I have `aurelia-templating-resources@^1.0.0-beta.1.0.1` installed with JSPM.

**Comment by martingust** [comment]
@heruan On [this](https://github.com/aurelia/templating-resources/blob/master/dist/amd/map-collection-strategy.js#L112) line change `overrideContext` to `bindingContext`.
