### ISSUE TITLE
Bind null for <option> value

### ISSUE THREAD

**Issue by StrahilKazlachev** [aurelia/templating-binding#73]
I have the following `<option value.bind="someValue"></option>`. If `someValue` is `null` the value attribute is set to `'undefined'`. Shouldn't it be `'null'`, and `'undefined'` when `someValue` is `undefined`?

**Comment by jdanyow** [comment]
An html `<option>` element's `value` attribute only accepts strings.  Anything you assign to it will be cast to a string.

To store `null`, `undefined`, numbers, objects, etc, use `model.bind` instead:

``` html
<option model.bind="someValue"></option>
```

**Comment by StrahilKazlachev** [comment]
I've missed that option, thanks.
