### ISSUE TITLE
Question regarding compose tag and binding.

### ISSUE THREAD

**Issue by Xenope** [aurelia/templating-binding#74]
Hello, 

I'm using the compose attribute to load a remote file and bind the values to "data":
![image](https://cloud.githubusercontent.com/assets/15614284/11892757/6057bc34-a56b-11e5-9564-59ea9b8611f9.png)

In this remote file I bind different values : 

![image](https://cloud.githubusercontent.com/assets/15614284/11892813/baa4c3d0-a56b-11e5-8a73-a0836b929a7a.png)

As you can see I bind  two values using "data" which is the one defined in the compose tag but I'm also able to bind values to the parent view-model. It's normal when I'm using the $parent keyword but i wonder if it's normal that I can access the parent context directly by using ${usr.ctc.ctcphnpostnum} or ${ctcphnpostnum} (two var defined in my parent view-model).

**Comment by StrahilKazlachev** [comment]
I think that `<compose>` doesn't create its own binding context.

**Comment by Xenope** [comment]
Just to be clear my compose attribute is inside a customElement, Doesn't have the customElement his own context and you won't be able to access the parent without $parent.

**Comment by jdanyow** [comment]
A custom element's template does not have access to the outer/parent scope.  Composed views do have access to the outer scope.  There have been some bugs related to these rules, the next release of the templating repo should address the outstanding issues.
