### ISSUE TITLE
Delegate not working on DOM event

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/templating-binding#76]
When raising a DOM event like this:

```
import {inject} from 'aurelia-framework';

@inject(Element)
export class Foo {

  constructor(element) {
    this.element = element;
  }

  attached(){
    let event = new CustomEvent('test', { 'detail': {a: 'b'}});
    this.element.dispatchEvent(event);
  }
}
```

it can't be registered to with a delegate it seems:

```
  <foo test.delegate="thisDoesNotGetCalled()"></foo>
```

plunker: http://plnkr.co/edit/xiu4Cp8DxY7Wqjtki9LG?p=preview

Is this expected?

**Comment by JeroenVinke** [comment]
Trigger is working fine by the way, just wonder if delegate should work also

**Comment by EisenbergEffect** [comment]
You will need to specify that your custom event bubbles.

**Comment by EisenbergEffect** [comment]
Add `bubbles: true` to your options that you are passing to the CustomEvent ctor.

**Comment by JeroenVinke** [comment]
Ah, yes, having it bubble fixed the problem. :+1:
