### ISSUE TITLE
Support binding RegExp literals

### ISSUE THREAD

**Issue by davismj** [aurelia/templating-binding#77]
I have a filter list value converter and I want to pass in a regexp literal:

`/[^anythingbutthis]/i`

This is currently a syntax error.

```
ERROR [app-router] Error: Parser Error: Unexpected token / at column 39 in [submission.samples | filter: { value: /[^anythingbutthis]/i }](…)
```

**Comment by EisenbergEffect** [comment]
Perhaps put it in a string and then convert it to a RegEx inside your converter? I have a feeling this would be a major task to implement. @jdanyow Any thoughts?

**Comment by davismj** [comment]
I did that. It would just be a really nice to have, I think.

For the record here's my filter code:

``` javascript
const REMATCH = /\/(.*)\/(\w*)/;

export class FilterValueConverter {
  toView(array, filter) {
    let keys = Object.keys(filter).filter((key) => filter[key]);
    if (!keys.length || keys.every((key) => filter[key] == null)) {
      return array;
    }
    return array.filter((item) => {
      return keys.some((key) => {

        let re = filter[key] || '';
        let match = REMATCH.exec(re);
        if (match) {
          re = new RegExp(match[1], match[2]);
        } else {
          re = new RegExp(re, 'i');
        }

        let value = item[key] || '';
        return re.test(value);
      });
    });
  }
}
```

**Comment by jdanyow** [comment]
It might be possible to add logic to the parser for this.  I'm not sure how much trouble that will be. This section in the grammar worries me a little bit, but may be a non-issue:

> ![grammar](http://i.imgur.com/dkJhHG8.png)
> http://www.ecma-international.org/ecma-262/5.1/#sec-7

It may be as easy as adding another condition [here](https://github.com/aurelia/binding/blob/master/src/parser.js#L280) and a `RegExLiteral` class to the AST.  Will experiment when I get a chance.  @davismj if you want to play around with it, I can try and answer any questions.

**Comment by EisenbergEffect** [comment]
I'd say skip it for now. We can consider it again after 1.0. I think there are more important things to tackle in the mean time, esp. since this isn't a show stopper.

**Comment by Alexander-Taran** [comment]
Stale since 2016
interesting use case though

**Comment by EisenbergEffect** [comment]
Going to close this. I don't want to expand the expression grammar if we can help it. A workaround for the above would be to register RegEx by name and then have the filter lookup the RegEx.

**Comment by davismj** [comment]
Get this out of the box with http://aurelia.plus
