### ISSUE TITLE
Nested repeat.for on two arrays causes uncaught TypeError / Repeat.items set to null

### ISSUE THREAD

**Issue by vuorinem** [aurelia/templating-binding#78]
Reproduce: http://plnkr.co/edit/3JaZYJbOv5dkO2y5P0vl

Binding a nested repeat.for with two different arrays of size 5 or more, then clearing the array and re-adding items, causes Repeat.items being set to null and throws `Uncaught TypeError: Cannot read property 'length' of null`.

Template:

```
<table>
  <tbody>
    <tr repeat.for="r of rows">
      <td repeat.for="c of cols">
        (${r.l},${c.l})
      </td>
    </tr>
  </tbody>
</table>
```

> @jsobell It appears to be related to the ModifyArrayObserver that gets added to the outer array

**Comment by jsobell** [comment]
Also reversing the order in which variables 'rows' and 'cols' have values pushed changes the error:

```
  this.rows.push(i);
  this.cols.push(i);
```

is different to

```
  this.cols.push(i);
  this.rows.push(i);
```

This transfers the null error from one repeat to the other.

**Comment by jdanyow** [comment]
thanks for the plunker and steps!

**Comment by jdanyow** [comment]
still an issue in latest build https://gist.run/?id=a2250b2a73da073a7a56
