### ISSUE TITLE
[QUESTION]Can we remove binding commands after compiling templates?

### ISSUE THREAD

**Issue by lgabeskiria** [aurelia/templating-binding#80]
![capture](https://cloud.githubusercontent.com/assets/7342339/13241995/a9382d4e-da09-11e5-841c-945ef9d98a87.PNG)

**Comment by EisenbergEffect** [comment]
Yes, it is safe to remove them. The compiler doesn't do that though in order to be more performant. But, if you wanted to remove them, it won't break anything.

**Comment by lgabeskiria** [comment]
How can I hook into compilation process to remove them automatically?

**Comment by EisenbergEffect** [comment]
There isn't a hook for that right now. Can I ask why you want to do that?

**Comment by lgabeskiria** [comment]
I want to hide internal implementation of my components.

**Comment by EisenbergEffect** [comment]
Please create another issue to request the ability to remove binding commands after compile. We may be able to al teast make an option for it.

**Comment by lgabeskiria** [comment]
Thank's.
