### ISSUE TITLE
Do not bind to children if parent element if.bind="false"

### ISSUE THREAD

**Issue by akircher** [aurelia/templating-binding#83]
I came across a strange behavior for a template like this

```
<div if.bind="nullOrObject">
   <input value.bind="nullOrObject.property">
</div>
```

In my view model, when I do `nullOrObject = null` aurelia resets it to an object and then because its an object the `<div></div>` keeps showing and never goes away. Changing it to this fixes the problem:

```
<div if.bind="nullOrObject">
   <input value.bind="nonProperty">
</div>
```

I have not thought this through completely but I think this because the templating engine is evaluating all the children inside the parent div even when `if` is `false`.  This causes an error because that means you are doing `null.property`. I think templating should not evaluate these at all.  There might be another solution however...

**Comment by EisenbergEffect** [comment]
It's not evaluating the children, I don't think. I believe this is an issue in the binding engine. @jdanyow Can you look into this? Is this an issue where the automatic object creation is biting us maybe?

**Comment by jdanyow** [comment]
yep- this issue: https://github.com/aurelia/binding/issues/205

**Comment by akircher** [comment]
If someone comes across this issue before the above issue is solved, here is my simple workaround to avoid the object being created automatically.

```
<div if.bind="nullOrObject">
   <input value.bind="(nullOrObject || {}).property">
</div>
```
