### ISSUE TITLE
Binding to the presence of an item in a collection

### ISSUE THREAD

**Issue by heruan** [aurelia/templating-binding#86]
Is it possibile to bind to the presence of an item in a collection, like `Set`, `Map` or `Array`?

For example, say we have `set1` and `set2`:

``` html
<li repeat.for="item of set1">
    ${item.value} <span if.bind="set2.has(item)">(present in set2)</span>
</li>
```

I tried this but it doesn't update when `set2` changes.

**Comment by jdanyow** [comment]
Would this work for you?
https://gist.run/?id=61b94e889c95d4336de7

@EisenbergEffect thoughts?

**Comment by EisenbergEffect** [comment]
Clever.

**Comment by jdanyow** [comment]
@heruan can this be closed?
