### ISSUE TITLE
ValueConverters returning HTML

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/templating-binding#87]
If I have a ValueConverter that produces HTML, like:

``` js
export class NewlinesValueConverter {
    public toView(value) {
        if (!value) {
            return null;
        }
        return value
            .replace(/\r\n/g, "\n")
            .replace(/[\r\n]/g, "<br/>");
    }
}
```

and I use it like so:

```
${note | newlines}
```

then the `<br/>` elements are escaped. Of course I can do

``` html
<span innerhtml.bind="note | newlines"></span>
```

but it'd be nice if I can configure this specific ValueConverter to not have its output escaped, say with a decorator. What do you think?

**Comment by EisenbergEffect** [comment]
Unfortunately, we can't change this. The interpolation binding mechanism sets `textContent`. The only way to bind html is to use innerhtml.bind. We don't want to make this any easier because of security concerns.
