### ISSUE TITLE
innerHTML bindings

### ISSUE THREAD

**Issue by caperavensoftware** [aurelia/templating-binding#96]
I am writing a test where I want to save and load html to and from profiles.
What is the best practice to add UI to a existing view during runtime and still get the binding enjine to work on that code.

e.g.

```
`<li click.delegate="itemSelected($event)">${course.Name}</li>\n`
```

This just being a small example, I know you can do lists using for loops in the html but this can be entire forms...

What I would like to do is swap out entire UI without navigating and then ask aurelia to evaluate the introduced html and set up the bindings as required.

**Comment by jdanyow** [comment]
Hi @caperavensoftware - check out the `TemplatingEngine` class in the docs. If you don't find what you need there- please post on stackoverflow under the [aurelia] tag with a gist that demonstrates your issue.
