### ISSUE TITLE
Parser/AST: string interpolation support

### ISSUE THREAD

**Issue by natrim** [aurelia/templating-binding#97]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0
- **Language:**
  TypeScript

**Current behavior:**
template literals don't work with ternary operator

```
<template bindable="what">
  <div>
    ${what ? `WHAT: ${what}!` : 'what?'}
  </div>
</template>
```

**Expected behavior:**
i expected it to work like

```
<template bindable="what">
  <div>
    ${what ? 'WHAT: '+what+'!' : 'what?'}
  </div>
</template>
```

**Comment by jdanyow** [comment]
Issue moved to [aurelia/binding #500](https://github.com/aurelia/binding/issues/500) via [**ZenHub**](https://www.zenhub.com/)
